name: Entrega Oficial - Express CEP

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest jinja2

    - name: Executar Testes Unitarios
      run: |
        python -m pytest --junitxml=resultado_testes.xml

    - name: Gerar Relatorio de Aceite Tecnico
      if: always()
      run: |
        python gera_relatorio.py

    - name: Enviar E-mail de Entrega Final
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.SENHAMAIL }}
        subject: "RELATÓRIO DE TESTES: Validação Express CEP - Matheus Trindade"
        to: "gustavo.luz@prof.uniso.br"
        from: "Automação EMAIL, DIA 20/03"
        body: |
          Prezado,

          Segue em anexo o Relatório de Aceite Técnico (RAT) referente aos testes automatizados das faixas de CEP da aplicação Express CEP.

          Status: Todos os casos de teste foram validados com sucesso via GitHub Actions.

          Atenciosamente,
          Matheus Trindade da Silva
          RA: 00121946
        attachments: termo_de_aceite.html