- name: Enviar E-mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.SENHAMAIL }}
        subject: "ENTREGA OFICIAL: Relatorio de Testes - Matheus"
        to: "matheustrindadedasilva@gmail.com" 
        from: "GitHub Actions"
        body: "Segue anexo o relatório de testes aprovados."
        attachments: termo_de_aceite.html